// Package main defines the portable tdx CI and release-build pipeline.
package main

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"dagger/tdx-ci/internal/dagger"
	"dagger/tdx-ci/pipeline"
)

const (
	goImage           = "golang:1.27.1-bookworm@sha256:648f440f42a0958804efb24df176f806f9d353b41f1c0627f666428e40310f6b"
	lintImage         = "golangci/golangci-lint:v2.13.2@sha256:ba07dffad130794ae79ebaa0056809d18c0168f3f846480ffd3eb6c04578b83d"
	actionlintVersion = "v1.7.12"
)

// TdxCi exposes the project's portable CI and release operations.
type TdxCi struct{}

// Ci runs every portable validation used by GitHub CI.
func (m *TdxCi) Ci(ctx context.Context, source *dagger.Directory) (string, error) {
	// Keep memory-intensive checks sequential so a developer's small Docker
	// VM does not run multiple Go/Rust compilers alongside terminal contracts.
	if _, err := m.Lint(ctx, source); err != nil {
		return "", fmt.Errorf("lint: %w", err)
	}

	checks := []struct {
		name string
		run  func() error
	}{
		{name: "usage-executable", run: func() error { _, err := m.usageCheck(ctx, source); return err }},
		{name: "rust-experiment", run: func() error { _, err := m.rustCheck(ctx, source); return err }},
		{name: "format", run: func() error { _, err := m.Format(ctx, source); return err }},
		{name: "vet", run: func() error { _, err := m.Vet(ctx, source); return err }},
		{name: "test", run: func() error { _, err := m.Test(ctx, source); return err }},
		{name: "coverage", run: func() error {
			file, err := m.CoverageBadge(ctx, source)
			if err != nil {
				return err
			}
			_, err = file.Contents(ctx)
			return err
		}},
		{name: "actionlint", run: func() error { _, err := m.Actionlint(ctx, source); return err }},
		{name: "pipeline-test", run: func() error { _, err := m.PipelineTest(ctx, source); return err }},
		{name: "build", run: func() error {
			_, err := m.VerifyBuild(ctx, source)
			return err
		}},
	}

	var failures []error
	for _, check := range checks {
		if err := check.run(); err != nil {
			failures = append(failures, fmt.Errorf("%s: %w", check.name, err))
		}
	}
	if err := errors.Join(failures...); err != nil {
		return "", err
	}
	return "portable CI passed", nil
}

// Format verifies that all Go source files are formatted.
func (m *TdxCi) Format(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.goBase(source).
		WithExec([]string{"bash", "-euc", `files=$(gofmt -l .); if [ -n "$files" ]; then echo "Go code is not formatted:"; echo "$files"; exit 1; fi`}).
		Stdout(ctx)
}

// Vet runs go vet across the application module.
func (m *TdxCi) Vet(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.goBase(source).
		WithExec([]string{"go", "vet", "./..."}).
		Stdout(ctx)
}

// Lint runs the pinned golangci-lint release.
func (m *TdxCi) Lint(ctx context.Context, source *dagger.Directory) (string, error) {
	return dag.Container().
		From(lintImage).
		WithDirectory("/src", cleanSource(source)).
		WithWorkdir("/src").
		WithMountedCache("/go/pkg/mod", dag.CacheVolume("tdx-go-mod-1.27.1")).
		WithMountedCache("/root/.cache/go-build", dag.CacheVolume("tdx-go-build-1.27.1")).
		WithMountedCache("/root/.cache/golangci-lint", dag.CacheVolume("tdx-golangci-lint-2.13.2")).
		WithExec([]string{"golangci-lint", "run", "--timeout=5m"}).
		Stdout(ctx)
}

// Test runs the race-enabled application test suite and records coverage.
func (m *TdxCi) Test(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.testContainer(source).Stdout(ctx)
}

// CoverageBadge returns the Shields-compatible badge generated by the test run.
func (m *TdxCi) CoverageBadge(ctx context.Context, source *dagger.Directory) (*dagger.File, error) {
	report, err := m.testContainer(source).
		WithExec([]string{"bash", "-euc", "set -o pipefail; go tool cover -func=/tmp/coverage.out | tail -n 1"}).
		Stdout(ctx)
	if err != nil {
		return nil, err
	}
	percent, err := pipeline.ParseTotalCoverage(report)
	if err != nil {
		return nil, err
	}
	payload, err := pipeline.CoverageBadgeJSON(percent)
	if err != nil {
		return nil, err
	}
	return dag.Directory().
		WithNewFile("coverage.json", payload).
		File("coverage.json"), nil
}

// Actionlint validates maintained GitHub Actions workflows.
func (m *TdxCi) Actionlint(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.goBase(source).
		WithExec([]string{"bash", "-euc", "go run github.com/rhysd/actionlint/cmd/actionlint@" + actionlintVersion + " .github/workflows/*.yml"}).
		Stdout(ctx)
}

// PipelineTest runs unit tests for pure pipeline logic.
func (m *TdxCi) PipelineTest(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.goBase(source).
		WithWorkdir("/src/.dagger").
		WithExec([]string{"go", "test", "./pipeline"}).
		Stdout(ctx)
}

// Build returns a deterministic Linux amd64 development binary.
func (m *TdxCi) Build(ctx context.Context, source *dagger.Directory) (*dagger.File, error) {
	metadata, err := readMetadata(ctx, source)
	if err != nil {
		return nil, err
	}
	target := pipeline.Target{Name: "tdx-linux-amd64", OS: "linux", Arch: "amd64"}
	return m.buildTarget(source, metadata, target), nil
}

// VerifyBuild executes the Linux artifact and checks its embedded version.
func (m *TdxCi) VerifyBuild(ctx context.Context, source *dagger.Directory) (string, error) {
	metadata, err := readMetadata(ctx, source)
	if err != nil {
		return "", err
	}
	binary, err := m.Build(ctx, source)
	if err != nil {
		return "", err
	}
	output, err := dag.Container().
		From(goImage).
		WithFile("/usr/local/bin/tdx", binary, dagger.ContainerWithFileOpts{Permissions: 0o755}).
		WithExec([]string{"tdx", "--version"}).
		Stdout(ctx)
	if err != nil {
		return "", err
	}
	want := "tdx v" + metadata.Version
	if strings.TrimSpace(output) != want {
		return "", fmt.Errorf("unexpected version output: got %q, want %q", strings.TrimSpace(output), want)
	}
	return output, nil
}

// ReleaseArtifacts returns all binaries published by a tagged release.
func (m *TdxCi) ReleaseArtifacts(ctx context.Context, source *dagger.Directory) (*dagger.Directory, error) {
	metadata, err := readMetadata(ctx, source)
	if err != nil {
		return nil, err
	}

	output := dag.Directory()
	for _, target := range pipeline.ReleaseTargets() {
		output = output.WithFile(target.Name, m.buildTarget(source, metadata, target))
	}
	return output, nil
}

func (m *TdxCi) goBase(source *dagger.Directory) *dagger.Container {
	return dag.Container().
		From(goImage).
		WithDirectory("/src", cleanSource(source)).
		WithWorkdir("/src").
		WithMountedCache("/go/pkg/mod", dag.CacheVolume("tdx-go-mod-1.27.1")).
		WithMountedCache("/root/.cache/go-build", dag.CacheVolume("tdx-go-build-1.27.1")).
		WithExec([]string{"go", "mod", "download"})
}

func (m *TdxCi) testContainer(source *dagger.Directory) *dagger.Container {
	return m.goBase(source).
		WithExec([]string{"go", "test", "-race", "-coverprofile=/tmp/coverage.out", "./..."})
}

func (m *TdxCi) buildTarget(source *dagger.Directory, metadata pipeline.Metadata, target pipeline.Target) *dagger.File {
	ldflags := fmt.Sprintf(
		"-s -w -X %s -X %s",
		strconv.Quote("main.Version="+metadata.Version),
		strconv.Quote("main.Description="+metadata.Description),
	)
	return m.goBase(source).
		WithEnvVariable("CGO_ENABLED", "0").
		WithEnvVariable("GOOS", target.OS).
		WithEnvVariable("GOARCH", target.Arch).
		WithExec([]string{"mkdir", "-p", "/out"}).
		WithExec([]string{"go", "build", "-trimpath", "-ldflags", ldflags, "-o", "/out/" + target.Name, "./cmd/tdx"}).
		File("/out/" + target.Name)
}

func cleanSource(source *dagger.Directory) *dagger.Directory {
	return source.
		WithoutDirectory(".git").
		WithoutDirectory("dist").
		WithoutFile("tdx").
		WithoutFile("coverage.out")
}

func readMetadata(ctx context.Context, source *dagger.Directory) (pipeline.Metadata, error) {
	contents, err := source.File("tdx.toml").Contents(ctx)
	if err != nil {
		return pipeline.Metadata{}, fmt.Errorf("read tdx.toml: %w", err)
	}
	metadata, err := pipeline.ParseMetadata(contents)
	if err != nil {
		return pipeline.Metadata{}, err
	}
	metadata.Description = strings.TrimSpace(metadata.Description)
	return metadata, nil
}

// rustCheck validates the optional parser experiment without running machine-dependent timings.
func (m *TdxCi) rustCheck(ctx context.Context, source *dagger.Directory) (string, error) {
	return dag.Container().
		From(goImage).
		WithEnvVariable("PATH", "/root/.cargo/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin").
		WithExec([]string{"bash", "-euc", `set -o pipefail
case "$(uname -m)" in
  x86_64) rust_target=x86_64-unknown-linux-gnu; rustup_sha=dda7234360b7f578ca8b0ddcb80145646fa61a67c1720a5abc7051b35c9fcb71 ;;
  aarch64) rust_target=aarch64-unknown-linux-gnu; rustup_sha=15f6e4ce9f583b929c996c91562bad6d4454f3281de858b02cdfdef615fac433 ;;
  *) echo "Unsupported Rust CI architecture" >&2; exit 1 ;;
esac
curl -fsSL --max-time 120 "https://static.rust-lang.org/rustup/archive/1.29.1/$rust_target/rustup-init" -o /tmp/rustup-init
printf '%s  /tmp/rustup-init\n' "$rustup_sha" | sha256sum -c -
chmod +x /tmp/rustup-init
/tmp/rustup-init -y --profile minimal --default-toolchain 1.98.1 --component rustfmt --component clippy`}).
		WithDirectory("/src", cleanSource(source)).
		WithWorkdir("/src/experiments/rust-eval/rust-probe").
		WithEnvVariable("CARGO_TARGET_DIR", "/tmp/rust-target").
		WithMountedCache("/root/.cargo/registry", dag.CacheVolume("tdx-rust-registry")).
		WithExec([]string{"cargo", "fmt", "--check"}).
		WithExec([]string{"cargo", "clippy", "--locked", "--", "-D", "warnings"}).
		WithExec([]string{"cargo", "test", "--locked"}).
		Stdout(ctx)
}

// usageCheck validates the language-neutral CLI and terminal contracts in Linux.
// The 100-hour accelerated campaign remains an explicit developer task.
func (m *TdxCi) usageCheck(ctx context.Context, source *dagger.Directory) (string, error) {
	return m.goBase(source).
		WithExec([]string{"go", "build", "-o", "/tmp/tdx-usage-binary", "./cmd/tdx"}).
		WithExec([]string{"go", "run", "./cmd/tdx-usage", "-driver", "cli", "-binary", "/tmp/tdx-usage-binary", "-sessions", "1", "-steps", "40"}).
		WithExec([]string{"go", "run", "./cmd/tdx-usage", "-driver", "structural", "-sessions", "1", "-steps", "60"}).
		WithExec([]string{"sh", "-ec", "apt-get update -qq && apt-get install -y --no-install-recommends python3"}).
		WithExec([]string{"python3", "scripts/usage-pty.py", "--binary", "/tmp/tdx-usage-binary"}).
		WithExec([]string{"bash", "scripts/test_release_notes.sh"}).
		WithExec([]string{"python3", "scripts/test_install.py"}).
		Stdout(ctx)
}
